export const asset = (name: string) => `${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}/currency/${name}.jpg`;
export type Item = { id: string; name: string; country: string; materials: string; form: string; denomination: string; tile: number; image?: string; imageRatio?: number; crop?: [number, number, number, number]; gate: string; idea: string };
export const items: Item[] = [
 {id:"ITEM-001",name:"X-Coin",country:"United States",materials:"Gold",form:"Union",denomination:"50 USD",tile:0,gate:"Join strength, edge safety and a costed fabrication trial.",idea:"Two familiar coins become one sculptural monetary object."},
 {id:"ITEM-002",name:"Diamond Tesseract",country:"United States",materials:"Synthetic diamond · inert metal core",form:"Cube",denomination:"250,000 USD",tile:1,gate:"Bonded coupons, then a subscale enclosure; joint strength, optical quality and thermal mismatch must pass predefined tests.",idea:"American iconography inside a transparent, multi-piece diamond enclosure. The flagship research proposal."},
 {id:"ITEM-003",name:"Liberty Torus",country:"United States",materials:"Platinum · sapphire · gold",form:"Torus",denomination:"10,000 USD",tile:2,gate:"Assembly tolerances, stone retention and handling durability.",idea:"A continuous ring makes monetary identity visible from every direction."},
 {id:"ITEM-004",name:"Harmony Sphere",country:"China",materials:"Jade · gold · proposed graphene",form:"Sphere",denomination:"50,000 CNY",tile:3,gate:"Define any functional role for graphene; validate jade mounting and impact resistance.",idea:"A spherical study of balance, layers and cultural identity."},
 {id:"ITEM-005",name:"Sora Prism",country:"Japan",materials:"Sapphire · titanium · silver",form:"Pyramid",denomination:"100,000 JPY",tile:4,gate:"Optical finishing, dissimilar-material joints and protected points.",idea:"A transparent prism carrying a miniature cultural landscape."},
 {id:"ITEM-006",name:"Axis Cube",country:"Germany",materials:"Tungsten · gold · optical quartz",form:"Cube",denomination:"25,000 EUR",tile:5,gate:"Mass budget, quartz enclosure joining and drop testing.",idea:"A dense metal center inside a clear architectural shell."},
 {id:"ITEM-007",name:"Alpine Core",country:"Switzerland",materials:"Rock crystal · gold · proposed alloy",form:"Rough",denomination:"50,000 CHF",tile:6,gate:"Specify alloy chemistry, inspect inclusions and characterize fracture behavior.",idea:"Irregular material becomes part of an object's recognizable identity."},
 {id:"ITEM-008",name:"Sand Blossom",country:"United Arab Emirates",materials:"Gold · diamond · silicon carbide",form:"Stellar",denomination:"100,000 AED",tile:7,gate:"Tip protection, stone retention and repeatable assembly.",idea:"A radial desert-inspired object, conceived as a ceremonial issue."},
 {id:"ITEM-009",name:"Infinity Lotus",country:"India",materials:"Diamond · gold · chalcedony",form:"Stellar",denomination:"100,000 INR",tile:8,gate:"Petal strength, impact survival and serviceable mounts.",idea:"Layered petals translate a familiar emblem into a physical object."},
 {id:"ITEM-010",name:"Southern Star",country:"Australia",materials:"Opal · titanium · gold",form:"Stellar",denomination:"50,000 AUD",tile:9,gate:"Opal stability, material compatibility and protected handling.",idea:"A star-shaped study in light, national identity and mixed materials."},
 {"id": "ITEM-011", "name": "Liberty & Eagle · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.003, 0.006, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-012", "name": "Standing Liberty · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.203, 0.006, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-013", "name": "Torch & Shield · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.403, 0.006, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-014", "name": "Heritage Profile · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.603, 0.006, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-015", "name": "Eagle Crown · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.803, 0.006, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-016", "name": "Union Shield · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.003, 0.3393333333333333, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-017", "name": "Prismatic Liberty · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.203, 0.3393333333333333, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-018", "name": "Eagle Medallion · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.403, 0.3393333333333333, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-019", "name": "Radiant Liberty · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.603, 0.3393333333333333, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-020", "name": "Heritage Relief · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.803, 0.3393333333333333, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-021", "name": "Starfield Liberty · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.003, 0.6726666666666666, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-022", "name": "Classical Seal · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.203, 0.6726666666666666, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-023", "name": "Union Emblem · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.403, 0.6726666666666666, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-024", "name": "Laurel Portrait · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.603, 0.6726666666666666, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-025", "name": "Twin Profiles · Relief", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-a", "imageRatio": 1.65875, "crop": [0.803, 0.6726666666666666, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-026", "name": "Liberty & Eagle · Faceted", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-b", "imageRatio": 1.6605633802816901, "crop": [0.003, 0.006, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-027", "name": "Standing Liberty · Faceted", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-b", "imageRatio": 1.6605633802816901, "crop": [0.203, 0.006, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-028", "name": "Torch & Shield · Faceted", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-b", "imageRatio": 1.6605633802816901, "crop": [0.403, 0.006, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-029", "name": "Heritage Profile · Faceted", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-b", "imageRatio": 1.6605633802816901, "crop": [0.603, 0.006, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-030", "name": "Eagle Crown · Faceted", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-b", "imageRatio": 1.6605633802816901, "crop": [0.803, 0.006, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-031", "name": "Union Shield · Faceted", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-b", "imageRatio": 1.6605633802816901, "crop": [0.003, 0.3393333333333333, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-032", "name": "Prismatic Liberty · Faceted", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-b", "imageRatio": 1.6605633802816901, "crop": [0.203, 0.3393333333333333, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-033", "name": "Eagle Medallion · Faceted", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-b", "imageRatio": 1.6605633802816901, "crop": [0.403, 0.3393333333333333, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-034", "name": "Radiant Liberty · Faceted", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-b", "imageRatio": 1.6605633802816901, "crop": [0.603, 0.3393333333333333, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-035", "name": "Heritage Relief · Faceted", "country": "United States", "materials": "Proposed diamond or optical-crystal body · metallic surface relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "relief-b", "imageRatio": 1.6605633802816901, "crop": [0.803, 0.3393333333333333, 0.194, 0.3213333333333333], "gate": "Choose crystal composition and size; test shallow relief or attached metal motifs on a small coupon. Deep sculpture and large flawless diamond volumes are not validated.", "idea": "A surface-iconography study selected for compact geometry and visible, inspectable faces. Optical appearance is illustrative; composition and dimensions need experimental validation."},
 {"id": "ITEM-036", "name": "Liberty Surface", "country": "United States", "materials": "Proposed optical crystal · metallic relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "liberty-relief", "imageRatio": 0.6712328767123288, "crop": [0.02, 0.14, 0.96, 0.77], "gate": "Specify achievable crystal size, relief process and edge protection; test an optical-crystal demonstrator before any diamond version.", "idea": "A selected physical-form study with readable faces and controlled edges. This rendering is a design reference, not a manufactured specimen."},
 {"id": "ITEM-037", "name": "Liberty Medallion", "country": "United States", "materials": "Proposed optical crystal · metallic relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "liberty-medallion", "imageRatio": 0.6712328767123288, "crop": [0.02, 0.14, 0.96, 0.77], "gate": "Specify achievable crystal size, relief process and edge protection; test an optical-crystal demonstrator before any diamond version.", "idea": "A selected physical-form study with readable faces and controlled edges. This rendering is a design reference, not a manufactured specimen."},
 {"id": "ITEM-038", "name": "Solid Metal Relief", "country": "United States", "materials": "Metal body · shallow relief", "form": "Solid", "denomination": "Unassigned", "tile": 0, "image": "solid-relief", "imageRatio": 0.6712328767123288, "crop": [0.02, 0.14, 0.96, 0.77], "gate": "Validate a modest-size solid metal demonstrator, surface finish and wear.", "idea": "A selected physical-form study with readable faces and controlled edges. This rendering is a design reference, not a manufactured specimen."},
 {"id": "ITEM-039", "name": "Clear Relief", "country": "United States", "materials": "Proposed optical crystal · metallic relief", "form": "Cube", "denomination": "Unassigned", "tile": 0, "image": "clear-relief", "imageRatio": 0.6712328767123288, "crop": [0.02, 0.14, 0.96, 0.77], "gate": "Specify achievable crystal size, relief process and edge protection; test an optical-crystal demonstrator before any diamond version.", "idea": "A selected physical-form study with readable faces and controlled edges. This rendering is a design reference, not a manufactured specimen."},
 {"id": "ITEM-040", "name": "Chamfered Liberty", "country": "United States", "materials": "Proposed optical crystal · metallic relief", "form": "Chamfered", "denomination": "Unassigned", "tile": 0, "image": "chamfered-relief", "imageRatio": 0.6714172604908947, "crop": [0.02, 0.14, 0.96, 0.77], "gate": "Specify achievable crystal size, relief process and edge protection; test an optical-crystal demonstrator before any diamond version.", "idea": "A selected physical-form study with readable faces and controlled edges. This rendering is a design reference, not a manufactured specimen."},
 {"id": "ITEM-041", "name": "Star Inlay Cube", "country": "United States", "materials": "Dark satin metal \u00b7 pale metal star inlays \u00b7 bronze seal", "form": "Inlaid", "denomination": "Unassigned", "tile": 0, "image": "star-inlay", "imageRatio": 0.6712328767123288, "crop": [0.09, 0.27, 0.83, 0.54], "gate": "Specify dimensions, relief depth, joining and surface process; validate a small material coupon before a full object.", "idea": "A reference-guided 3D interpretation of the supplied concept. Visible design features are modeled; hidden surfaces and portrait geometry are inferred. Source-quality equivalence has not been established."},
 {"id": "ITEM-042", "name": "Liberty Filigree Vault", "country": "United States", "materials": "Proposed crystal \u00b7 silver relief \u00b7 gold lattice", "form": "Filigree", "denomination": "Unassigned", "tile": 0, "image": "liberty-filigree", "imageRatio": 0.971304347826087, "crop": [0.015, 0.04, 0.97, 0.94], "gate": "Specify dimensions, relief depth, joining and surface process; validate a small material coupon before a full object.", "idea": "A reference-guided 3D interpretation of the supplied concept. Visible design features are modeled; hidden surfaces and portrait geometry are inferred. Source-quality equivalence has not been established."},
 {"id": "ITEM-043", "name": "Franklin Crystal Reserve", "country": "United States", "materials": "Proposed crystal \u00b7 engraved silver panels \u00b7 gold interior", "form": "Portrait", "denomination": "Unassigned", "tile": 0, "image": "franklin-crystal", "imageRatio": 0.6712328767123288, "crop": [0.015, 0.11, 0.97, 0.82], "gate": "Specify dimensions, relief depth, joining and surface process; validate a small material coupon before a full object.", "idea": "A reference-guided 3D interpretation of the supplied concept. Visible design features are modeled; hidden surfaces and portrait geometry are inferred. Source-quality equivalence has not been established."},
];
export const years = [
 [2027,"Prove the interface","Small bonded coupons and independently recorded failures.","A subscale diamond enclosure in a research collection.","Joining fails; retain solid forms or mechanically retained display prototypes."],
 [2028,"Make one repeatable object","Repeat coupon results, then document assembly yield and actual costs.","A small family of numbered demonstrators.","Yield or cost prevents repeat manufacture."],
 [2029,"Test identity and durability","Blind authentication trials, wear, impact and temperature testing.","Independent laboratories compare object fingerprints.","Security signals are unstable or too easy to imitate."],
 [2030,"Invite national interpretation","Publish technical evidence and seek a named institutional evaluation route.","The ten-object world collection becomes an international exhibition.","No institutional sponsor emerges; remain a research/art collection."],
 [2031,"Design for custody","Document inspection, custody transfer, damage and loss procedures.","Museum and vault pilots evaluate physical verification.","Handling and insurance costs outweigh practical value."],
 [2032,"Evaluate pilot issuance","Obtain jurisdiction-specific authority and a defined issuing partner before any currency pilot.","One authorized experimental issue becomes possible.","No legal authority or issuer: no monetary issuance."],
 [2033,"Compare verification methods","Independent round-robin measurement and reproducibility data.","Several institutions read the same physical reference records.","Readers disagree; interoperability remains unresolved."],
 [2034,"Test circulation boundaries","Measure real demand, redemption operations and total lifecycle costs.","A limited pilot explores transfers between approved custodians.","No viable demand or redemption mechanism."],
 [2035,"Explore a second jurisdiction","Require a separate sponsor, legal review and locally appropriate design.","Two independent national programs compare voluntary standards.","A first pilot does not translate across borders."],
 [2036,"Establish repair and retirement","Publish damage thresholds, replacement and retirement controls.","Objects acquire documented physical histories.","Lifecycle support costs make continuation impractical."],
 [2037,"Audit manufacturing scale","Independent yield, energy, supply and environmental accounting.","Selected forms move beyond bespoke production.","Capacity or resource constraints keep production small."],
 [2038,"Evaluate cross-border compatibility","Test verification and custody agreements under each participant's rules.","A shared reference format links distinct national objects.","Jurisdictions choose incompatible requirements."],
 [2039,"Review public usefulness","Publish independent findings on access, fraud, cost and use.","A wider public collection connects material culture and money.","Benefits do not justify expansion; limit or retire the pilot."],
 [2040,"Choose the enduring forms","Continue only forms supported by repeatable evidence and willing authorized institutions.","A plural global family of 3D monetary objects, if all preceding gates succeed.","A durable museum and research archive, even without currency adoption."],
] as const;
export const sources = [
 {title:"Direct-bonded diamond membranes (2024)",url:"https://www.nature.com/articles/s41467-024-53150-3",note:"Demonstrates membrane interfaces; does not validate this large diamond enclosure."},
 {title:"U.S. Mint: design and selection",url:"https://www.usmint.gov/news/inside-the-mint/how-coins-are-made-design-and-selection-process",note:"Describes the role of legislation and review in U.S. coin programs; not an approval of ITEM."},
 {title:"USPTO: provisional applications",url:"https://www.uspto.gov/patents/basics/apply/provisional-application",note:"Filing guidance. Concept illustrations alone establish no patent-pending status."},
];
export const plates = ["world","overview","exotic","evolution","rarity","family","solid","trajectory","catalog","pyramid","star-inlay","liberty-filigree","franklin-crystal"];

export const imageFor = (item: Item) => item.image ?? "world";
export const cropFor = (item: Item): [number, number, number, number] => item.crop ?? [(item.tile % 5) * .2 + .004, item.tile < 5 ? .19 : .69, .192, .21];

export const frameAspect = (item: Item) => { const crop = cropFor(item); return (item.imageRatio ?? 1.5) * crop[2] / crop[3]; };
