import * as T from 'three';
import {VENDING,TUNNEL,SOUL_TRADER,type Economy,type SoulCluster} from './game-economy.ts';
import {characterModel} from './character-models.ts';
import {batchModel} from './model-utils.ts';
export function buildEconomyWorld(){
 const root=new T.Group();root.name='Supply network / Uk’onu’okele';const collisions:T.Object3D[]=[];
 const metal=new T.MeshStandardMaterial({color:0x243b3b,roughness:.5,metalness:.7}),stone=new T.MeshStandardMaterial({color:0x303238,roughness:.95}),green=new T.MeshBasicMaterial({color:0x88efb4}),cyan=new T.MeshBasicMaterial({color:0x81ddff,transparent:true,opacity:.7});
 const mesh=(g:T.BufferGeometry,m:T.Material,x:number,y:number,z:number,parent=root)=>{const o=new T.Mesh(g,m);o.position.set(x,y,z);parent.add(o);return o;};
 VENDING.forEach((v,i)=>{const group=new T.Group();group.name=`USD supply machine ${i+1}`;group.position.set(v.x,0,v.z);root.add(group);const body=mesh(new T.BoxGeometry(1.6,2.6,1),metal,0,1.3,0,group);collisions.push(body);const decor=new T.Group();group.add(decor);mesh(new T.BoxGeometry(1.15,1.4,.08),new T.MeshStandardMaterial({color:0x172529}),0,1.55,-.54,decor);for(let j=0;j<6;j++){mesh(new T.BoxGeometry(.26,.34,.08),j%2?stone:metal,(j%3-1)*.34,1.1+Math.floor(j/3)*.6,-.6,decor);}mesh(new T.BoxGeometry(1.3,.15,.06),green,0,2.42,-.56,decor);mesh(new T.BoxGeometry(.4,.5,.08),green,.45,.42,-.56,decor);batchModel(decor);});
 const {x,z}=TUNNEL;
 const box=(w:number,h:number,d:number,px:number,py:number,pz:number,m=stone)=>{const o=mesh(new T.BoxGeometry(w,h,d),m,px,py,pz);collisions.push(o);return o;};
 box(1,7,40,x-4.5,-2.5,z+20);box(1,7,40,x+4.5,-2.5,z+20);box(9,7,1,x,-2.5,z+40.5);box(8,.4,24,x,-.05,z+28);box(8,.3,24,x,-6.15,z+28);
 // Sloped entrance matches tunnelGround: 6m descent over 16m.
 const ramp=new T.BufferGeometry();ramp.setAttribute('position',new T.Float32BufferAttribute([x-4,0,z,x-4,-6,z+16,x+4,0,z,x+4,0,z,x-4,-6,z+16,x+4,-6,z+16],3));ramp.computeVertexNormals();const rampMesh=new T.Mesh(ramp,new T.MeshStandardMaterial({color:0x54545b,side:T.DoubleSide}));root.add(rampMesh);collisions.push(rampMesh);
 for(let i=0;i<5;i++){mesh(new T.BoxGeometry(.12,.12,2),green,x-3.8,-1-i,z+3+i*3);const arch=new T.Mesh(new T.TorusGeometry(3.8,.15,6,20,Math.PI),metal);arch.position.set(x,-5,z+18+i*4);root.add(arch);}const lamp=new T.PointLight(0x9ccde0,18,28,2);lamp.position.set(x,-2,z+29);root.add(lamp);
 const trader=characterModel(0x433c56,'refugee');trader.name=SOUL_TRADER.name;trader.position.set(SOUL_TRADER.x,-6,SOUL_TRADER.z);root.add(trader);box(2.5,1,1,x,-5.5,z+32,metal);
 const held=new T.Group();held.name='Skull of Uk’onu’okele';root.add(held);held.visible=false;const bone=new T.MeshStandardMaterial({color:0xe7dcc3,roughness:.55,metalness:.1});const dark=new T.MeshBasicMaterial({color:0x111323});
 const cranium=mesh(new T.SphereGeometry(.22,16,12),bone,0,.08,0,held);cranium.scale.set(1,1.18,.85);mesh(new T.BoxGeometry(.28,.14,.25),bone,0,-.13,-.01,held);for(const side of [-1,1]){const eye=mesh(new T.SphereGeometry(.078,12,8),dark,side*.09,.075,-.175,held);eye.scale.z=.4;mesh(new T.SphereGeometry(.025,8,6),cyan,side*.09,.075,-.208,held);}mesh(new T.ConeGeometry(.04,.07,3),dark,0,-.02,-.18,held);for(let i=0;i<7;i++)mesh(new T.BoxGeometry(.025,.07,.045),bone,(i-3)*.035,-.17,-.15,held);batchModel(held);
 const souls=Array.from({length:48},()=>{const group=new T.Group();group.visible=false;root.add(group);const glow=mesh(new T.SphereGeometry(.23,10,8),cyan,0,0,0,group);glow.scale.y=1.35;const tail=mesh(new T.ConeGeometry(.18,.9,8),cyan,0,-.45,0,group);tail.rotation.z=Math.PI;for(const side of [-1,1])mesh(new T.SphereGeometry(.035,6,4),green,side*.08,.04,-.2,group);return group;});
 const tether=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3()]),new T.LineBasicMaterial({color:0xa5e8ff,transparent:true,opacity:.8}));tether.visible=false;root.add(tether);let tetherAge=0;
 const gear=new T.Group();gear.name='Purchased equipment';const helmet=mesh(new T.SphereGeometry(.21,14,10,0,Math.PI*2,0,Math.PI*.62),metal,0,1.75,0,gear);const exo=new T.Group();gear.add(exo);for(const side of [-1,1]){mesh(new T.CylinderGeometry(.035,.035,.85,6),metal,side*.27,1.04,.12,exo);mesh(new T.SphereGeometry(.08,8,6),green,side*.29,1.36,.1,exo);}const pack=new T.Group();gear.add(pack);const jets:T.Mesh[]=[];for(const side of [-1,1]){mesh(new T.CylinderGeometry(.1,.1,.48,10),metal,side*.2,1.2,.35,pack);const flame=mesh(new T.ConeGeometry(.1,.45,8),cyan,side*.2,.72,.35,pack);flame.rotation.z=Math.PI;jets.push(flame);}const nanites=mesh(new T.TorusGeometry(.15,.018,6,20),cyan,0,1.18,-.3,gear);
 return {root,held,gear,trader,collisions,souls,tether,update(e:Economy,visible:boolean,point:{x:number;y:number;z:number},age:number,dt:number,flying:boolean){const nearby=visible?e.pending.filter(s=>Math.hypot(s.x-point.x,s.y-point.y,s.z-point.z)<100).sort((a,b)=>Math.hypot(a.x-point.x,a.z-point.z)-Math.hypot(b.x-point.x,b.z-point.z)).slice(0,souls.length):[];souls.forEach((o,i)=>{const s=nearby[i];o.visible=!!s;if(s){o.position.set(s.x,s.y+.3+Math.sin(age*2+i)*.22,s.z);o.rotation.y=-age*.2;}});helmet.visible=e.helmet;exo.visible=e.exo;pack.visible=e.jetpack;nanites.visible=e.nanites;jets.forEach(j=>j.visible=flying);tetherAge=Math.max(0,tetherAge-dt);tether.visible=visible&&tetherAge>0;},absorb(s:SoulCluster,origin:T.Vector3){const a=tether.geometry.getAttribute('position') as T.BufferAttribute;a.setXYZ(0,s.x,s.y,s.z);a.setXYZ(1,origin.x,origin.y,origin.z);a.needsUpdate=true;tether.geometry.computeBoundingSphere();tetherAge=.2;tether.visible=true;},dispose(){const geos=new Set<T.BufferGeometry>(),mats=new Set<T.Material>();[root,gear].forEach(g=>g.traverse(o=>{const m=o as T.Mesh;if(m.geometry)geos.add(m.geometry);if(m.material)(Array.isArray(m.material)?m.material:[m.material]).forEach(v=>mats.add(v));}));geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());}};
}
