// Generated by scripts/write-build-manifest.mjs before every production build.
// Development defaults are explicit and are never presented as production facts.
export type BuildManifest = {
  product: string;
  repository: string;
  runtimePath: string;
  buildMode: "human-directed-ai-assisted";
  productionCommit: string;
  deployedAt: string;
  steelFold: number;
  openCompletionIssue: number;
};

export const buildManifest: BuildManifest = {
  product: "aetimm.com",
  repository: "injammed/ABYS",
  runtimePath: "apps/item-web",
  buildMode: "human-directed-ai-assisted",
  productionCommit: "development",
  deployedAt: "development",
  steelFold: 3,
  openCompletionIssue: 39,
};
