// Generated by scripts/write-build-manifest.mjs before every production build.
// Development defaults are explicit and are never presented as production facts.
export const buildManifest = {
  product: "aetimm.com",
  repository: "injammed/ABYS",
  runtimePath: "apps/item-web",
  buildMode: "human-directed-ai-assisted",
  productionCommit: "development",
  deployedAt: "development",
  steelFold: 3,
  openCompletionIssue: 39,
} as const;

export type BuildManifest = typeof buildManifest;
