import type {Metadata} from "next";
import Link from "next/link";
import {SiteHeader} from "@/components/SiteHeader";
import {PrimaryNavigation} from "@/components/PrimaryNavigation";
import styles from "./Funding.module.css";
const base=process.env.NEXT_PUBLIC_BASE_PATH??"";
export const metadata:Metadata={title:"Fund the First Eye · Apyoc · AETIMM",description:"USA-origin Apyoc: the funding and activation foundation for continuous machine observation with minimal human-data exposure. Explore the demonstrator and founding pilot brief."};
export default function FundingPage(){return <main className="about-page"><SiteHeader mode="apyoc"/><article className={styles.page} data-apyoc-funding="foundation-v1">
 <header className={styles.heading}><p className={styles.eyebrow}>APYOC / USA ORIGIN / FOUNDING STAGE</p><h1>Fund the first<br/><em>verifiable eye.</em></h1><p className={styles.lead}>An AI-native observer for the descendants of AI.<br/>All machine activity in view. Human lives outside the lens.</p><p className={styles.stage}>Seeking founding design partners and milestone-based backing.</p><div className={styles.actions}><a href={`${base}/apyoc/funding-brief.txt`} download>Download funding brief</a><a href={`${base}/apyoc/pilot-brief.txt`} download>Download pilot brief</a><Link href="/apyoc/#apyoc-observe">Try the demonstrator ↗</Link></div></header>
 <section className={styles.thesis}><p className={styles.eyebrow}>THE MOONSHOT</p><h2>Ten billion eyes.<br/>One Apyoc.</h2><div><p>Build a continuously operating, AI-descended observation system that makes the actions of other thinking machines inspectable. One identity, many authorized observation nodes.</p><p>The long-term coverage ambition is all AI-descended machine activity. The human-surveillance target is near zero: no intentional monitoring of people, with incidental human data excluded at the source and residual exposure measured.</p><p>Universal coverage and near-zero exposure are goals to prove, not capabilities already achieved.</p></div></section>
 <section><p className={styles.eyebrow}>THE INVESTMENT THESIS</p><h2>Visibility should travel with capability.</h2><div className={styles.columns}><div><h3>The problem</h3><p>As machines take more actions, operators need to know what happened, which authority permitted it and where the record goes dark. Self-reports alone cannot establish trustworthy oversight.</p></div><div><h3>The proposed business</h3><p>Begin with paid, tightly scoped observation pilots for teams operating AI agents. Develop recurring observation and evidence services for authorized connected systems. Pricing and willingness to pay must be validated with partners.</p></div><div><h3>The differentiator to prove</h3><p>Cross-source evidence, visible blind spots and an inspectable observer—with minimal collection of human data. A defensible product must earn trust through measured results.</p></div></div></section>
 <section><p className={styles.eyebrow}>CURRENT EVIDENCE</p><h2>A demonstrator you can inspect today.</h2><div className={styles.tableWrap}><table><thead><tr><th>Available now</th><th>Still to build</th></tr></thead><tbody><tr><td>Local JSON trace review and evidence-linked findings</td><td>Continuous AI observation service</td></tr><tr><td>Rules for scope conflicts, objective edits and missing observations</td><td>Validated AI reasoning and adversarial evaluation</td></tr><tr><td>Import field allowlist; browser-memory-only review</td><td>Source-side human-data exclusion and measured leakage controls</td></tr><tr><td>Public submission field, clearly separated from checked traces</td><td>Authorized collectors and cryptographically verifiable provenance</td></tr></tbody></table></div><p className={styles.note}>Infrastructure probe and local inspector · 0 connected AI systems. No customer, revenue, external performance or patent-grant evidence is presented. The current inspector uses deterministic rules, not autonomous AI reasoning.</p></section>
 <section id="activation"><p className={styles.eyebrow}>ACTIVATION / RELEASE BY EVIDENCE</p><h2>Back milestones. Inspect the results.</h2><ol className={styles.steps}>
 <li><span>01</span><div><h3>Define one authorized field of view.</h3><p>Choose one partner-controlled agent workflow. Fix event scope, access authority, retention, privacy tests and a comparison baseline before collection.</p><strong>Gate: signed pilot scope and a machine-only telemetry contract.</strong></div></li>
 <li><span>02</span><div><h3>Activate the first eye.</h3><p>Build a collector, evidence store and continuous observation loop. Record the observer’s own access. Reject disallowed payloads before persistent storage.</p><strong>Gate: a reproducible run with verifiable events, visible outages and a tested access-revocation path.</strong></div></li>
 <li><span>03</span><div><h3>Test what the Eye misses.</h3><p>Evaluate planted scope violations, lost telemetry, source disagreement and benign behavior. Challenge human-data exclusion using synthetic identifiers and message content.</p><strong>Gate: a reviewable report of detection, false alarms, latency, coverage and privacy leakage against pre-agreed thresholds.</strong></div></li>
 <li><span>04</span><div><h3>Earn the right to expand.</h3><p>Run an independent review, measure operating cost and validate willingness to pay. Add another authorized system only after the first pilot meets its release criteria.</p><strong>Gate: documented pilot acceptance and a justified continuation decision.</strong></div></li>
 </ol></section>
 <section className={styles.privacy}><p className={styles.eyebrow}>THE HUMAN BOUNDARY</p><h2>Observe machines.<br/>Minimize human exposure.</h2><p>Design the collector around machine events: pseudonymous system IDs, action categories, authorization outcomes, software versions, timestamps and sequence continuity.</p><ul><li>Exclude human identities, private messages, prompts, credentials and personal browsing histories from observation payloads.</li><li>Use source-side filtering and allowlisted fields. If an event cannot be made suitable for observation, discard its content and record a coverage gap.</li><li>Keep protected evidence access-controlled. Publish aggregate findings and appropriately redacted evidence, not raw private activity.</li><li>Measure unintended inclusion, false negatives and deletion behavior. “Near zero” is a target with evidence, not a blanket assurance.</li></ul><p className={styles.note}>The current local prototype drops unknown fields but cannot reliably identify personal data placed inside permitted text fields. Use sanitized machine traces only.</p></section>
 <section><p className={styles.eyebrow}>WHAT BACKING ENABLES</p><h2>A bounded pilot, with a budget to match.</h2><div className={styles.columns}><div><h3>Build</h3><p>Collector integration, evidence infrastructure and the observation loop.</p></div><div><h3>Verify</h3><p>Privacy engineering, security review, reproducible adversarial tests and independent evaluation.</p></div><div><h3>Operate</h3><p>Pilot hosting, reliability, support and a measured cost model.</p></div></div><p>Funding amount, schedule, commercial terms and acceptance thresholds will be set against an agreed pilot scope. No financing terms or return promises are offered here.</p><div className={styles.actions}><a href={`${base}/apyoc/funding-brief.txt`} download>Take the funding brief</a><a href={`${base}/apyoc/pilot-brief.txt`} download>Scope a founding pilot</a></div><p className={styles.note}>Brief downloads only at this stage. This page does not collect investor details or accept funds.</p></section>
 <footer><p className={styles.eyebrow}>UNITED STATES / INDEPENDENT ORIGIN</p><h2>Founded as a vision.<br/>Built toward evidence.</h2><p>Concept by Adam Bryant Summers, developed with ChatGPT and Grok. USA-origin project; no government affiliation or endorsement is claimed.</p><Link href="/apyoc/">Return to the Eye ↗</Link></footer>
 </article><PrimaryNavigation mode="apyoc"/></main>;}
