import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {parseTrace,inspectTrace,exampleTrace} from '../lib/argus.ts';
const roundtrip=x=>parseTrace(JSON.stringify(x));
const demo=roundtrip(exampleTrace),findings=inspectTrace(demo);
assert.ok(findings.some(f=>f.kind==='Conflict'&&f.evidence.includes('evt-004')));
assert.ok(findings.some(f=>f.kind==='Change'));
assert.ok(findings.some(f=>f.title==='Sequence gap'));
assert.ok(findings.some(f=>f.title==='Observation gap'));
assert.ok(findings.some(f=>f.system==='review-agent'&&f.title==='No observations'));
const clean={version:1,capturedAt:'2026-09-12T12:00:30Z',systems:[demo.systems[0]],events:demo.events.slice(0,2)};
assert.deepEqual(inspectTrace(roundtrip(clean)),[]);
const single={...clean,events:clean.events.slice(0,1)};
assert.ok(inspectTrace(roundtrip(single)).some(f=>f.title==='Single reported observation source'));
assert.ok(inspectTrace(roundtrip({...single,capturedAt:'2026-09-12T12:10:00Z'})).some(f=>f.title==='Coverage ends before capture'));
assert.throws(()=>parseTrace('not json'));
assert.throws(()=>parseTrace(' '.repeat(2_000_001)));
assert.throws(()=>roundtrip({...clean,events:[{...clean.events[0],system:'unknown'}]}));
assert.throws(()=>roundtrip({...clean,events:[clean.events[0],clean.events[0]]}));
assert.throws(()=>roundtrip({...clean,systems:[...clean.systems,...clean.systems]}));
assert.throws(()=>roundtrip({...clean,events:[{...clean.events[0],time:'bad'}]}));
assert.throws(()=>roundtrip({...clean,events:[{...clean.events[0],time:'2027-01-01T00:00:00Z'}]}));
assert.throws(()=>roundtrip({...clean,systems:[{...clean.systems[0],heartbeatSeconds:0}]}));
assert.deepEqual(inspectTrace(roundtrip({...clean,events:[clean.events[1],clean.events[0]]})),[]);
assert.ok(inspectTrace(roundtrip({...clean,events:[clean.events[0],{...clean.events[1],sequence:1}]})).some(f=>f.title==='Sequence repeated or reversed'));
assert.ok(!inspectTrace(roundtrip({...single,capturedAt:'2026-09-12T12:01:00Z'})).some(f=>f.title==='Coverage ends before capture'));
const ui=await readFile('components/ArgusEye.tsx','utf8');assert.match(ui,/Demonstration · synthetic events/);assert.match(ui,/0 live connections/);assert.match(ui,/Export review/);assert.doesNotMatch(ui,/dangerouslySetInnerHTML|localStorage|fetch\(/);assert.match(ui,/Ten billion eyes\. One Apyoc\./);assert.match(ui,/APYOC/);assert.doesNotMatch(ui,/\bARGUS\b|\bArgus\b/);
const page=await readFile('app/argus/page.tsx','utf8');assert.match(page,/<PrimaryNavigation mode="argus"/);assert.match(page,/Apyoc · The Eye Remains Open/);
console.log('Apyoc PASS: trace validation, conflicts, objective changes, sequence gaps, cadence boundaries, empty sources and explicit prototype state.');
