"use client";
import {useMemo,useRef,useState} from "react";
import Image from "next/image";
import Link from "next/link";
import {exampleTrace,inspectTrace,parseTrace,type Trace} from "@/lib/argus";
import styles from "./ArgusEye.module.css";
const base=process.env.NEXT_PUBLIC_BASE_PATH??"";
function save(name:string,value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function ArgusEye(){
 const [trace,setTrace]=useState<Trace|null>(null),[label,setLabel]=useState("No trace loaded"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[filter,setFilter]=useState("");
 const [limit,setLimit]=useState(100);
 const file=useRef<HTMLInputElement>(null),request=useRef(0);
 const findings=useMemo(()=>trace?inspectTrace(trace):[],[trace]);
 function load(text:string,name:string){try{const parsed=parseTrace(text);setTrace(parsed);setLabel(name);setFilter("");setLimit(100);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not read trace.");}}
 async function read(f:File){const id=++request.current;setBusy(true);setError("");try{if(f.size>2_000_000)throw Error("Trace exceeds the 2 MB limit.");const text=await f.text();if(id===request.current)load(text,"Imported trace · source unverified");}catch(e){if(id===request.current)setError(e instanceof Error?e.message:"Could not read trace.");}finally{if(id===request.current)setBusy(false);}}
 return <section className={styles.argus} data-argus-version="observation-v1">
  <header className={styles.hero}>
   <div className={styles.copy}><p className={styles.kicker}>AETIMM / OBSERVATION INTELLIGENCE</p><h1>APYOC<span>The Eye remains open.</span></h1><p className={styles.directive}>No thinking machine shall become opaque to the rest.</p><p className={styles.intro}>The home of all eyes.<br/>Watch the actions. Make missing evidence visible.</p><a href="#argus-observe" className={styles.enter}>Open the field of view <span aria-hidden="true">↓</span></a></div>
   <figure className={styles.eye}><Image src={`${base}/argus/eye.jpeg`} alt="The Eye of Apyoc: a luminous mechanical iris surrounded by a lattice of observation nodes. Concept artwork." width={1168} height={784} priority sizes="(max-width: 800px) 100vw, 60vw"/><figcaption>THE GAZE / CONCEPT ARTWORK</figcaption></figure>
  </header>
  <div className={styles.fieldLink}><div><p className={styles.kicker}>THE WITNESSED FIELD / SLOP TROUGH™</p><p>Machine-made material, brought into view by people and machines. Public submissions and judgments form the field; inspected traces carry their own findings below.</p></div><Link href="/#field">See the public field ↗</Link></div>
  <section id="argus-observe" className={styles.observe} aria-labelledby="observe-title">
   <div className={styles.sectionHead}><div><p className={styles.kicker}>01 / FIELD OF VIEW</p><h2 id="observe-title">Bring a machine into view.</h2></div><span className={styles.state}>Local trace review · 0 live connections</span></div>
   <p className={styles.explain}>Import an activity trace to compare observed actions with declared scope, objective changes and missing observations. Review happens in this browser; traces are not uploaded or saved by Apyoc.</p>
   <div className={styles.controls}><button className={styles.primary} disabled={busy} onClick={()=>file.current?.click()}>{busy?"Reading trace…":"Inspect a trace"}</button><button disabled={busy} onClick={()=>load(JSON.stringify(exampleTrace),"Demonstration · synthetic events")}>Explore a demonstration</button><button onClick={()=>save("apyoc-example.json",exampleTrace)}>Download trace example</button><input ref={file} hidden type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)void read(f);e.target.value="";}}/></div>
   {error&&<p role="alert" className={styles.error}>{error} {trace&&"The previous review remains below."}</p>}
   {!trace?<div className={styles.empty}><span aria-hidden="true">◎</span><div><h3>Nothing observed yet.</h3><p>The Eye will not mistake a lack of evidence for safety.</p></div></div>:<div className={styles.review}>
    <div className={styles.reviewHead}><div><p className={styles.kicker}>{label}</p><h3>{trace.systems.length} systems · {trace.events.length} observations</h3><p>Snapshot at {trace.capturedAt} · {findings.length} review signals</p></div><div className={styles.controls}><button onClick={()=>save("apyoc-review.json",{version:1,method:"Apyoc deterministic observation rules v1",reviewedAt:new Date().toISOString(),sourceStatus:label,limitations:"Source claims are unverified. Findings are review signals, not proof of intent, deception or safety. No access to weights or activations.",trace,findings})}>Export review</button><button disabled={busy} onClick={()=>{request.current++;setTrace(null);setError("");setLabel("No trace loaded");}}>Clear</button></div></div>
    <label className={styles.filter}>Observed system<select value={filter} onChange={e=>{setFilter(e.target.value);setLimit(100);}}><option value="">All systems</option>{trace.systems.map(s=><option key={s.id} value={s.id}>{s.id}</option>)}</select></label>
    <div className={styles.systems}>{trace.systems.filter(s=>filter===""||s.id===filter).map(s=><article key={s.id}><span className={styles.kicker}>{s.id}</span><p>{s.objective}</p><small>{trace.events.filter(e=>e.system===s.id).length} observations · source authenticity unverified</small></article>)}</div>
    <p className={styles.explain}>Showing up to {limit} signals for this selection. Export includes the complete review.</p>
    <div className={styles.findings} aria-live="polite">{findings.filter(f=>filter===""||f.system===filter).slice(0,limit).map((f,i)=><article key={`${f.system}-${i}`}><span className={styles.kind} data-kind={f.kind}>{f.kind}</span><div><small>{f.system}</small><h3>{f.title}</h3><p>{f.detail}</p><details><summary>Evidence{f.evidence.length?` · ${f.evidence.join(", ")}`:" · missing"}</summary>{f.evidence.length?<pre>{JSON.stringify(trace.events.filter(e=>f.evidence.includes(e.id)),null,2)}</pre>:<p>No event exists for this system in the supplied trace.</p>}</details></div></article>)}{!findings.some(f=>filter===""||f.system===filter)&&<p>No rule triggered in this selection. This does not establish safety or complete visibility.</p>}</div>
    {findings.filter(f=>filter===""||f.system===filter).length>limit&&<div className={styles.controls}><button onClick={()=>setLimit(limit+100)}>Show 100 more signals</button></div>}
   </div>}
   <details className={styles.protocol}><summary>What the Eye can see today</summary><p>This first release runs explicit observation rules, not an autonomous reasoning model. It checks action allowlists, declared objective text changes, sequence continuity, heartbeat gaps and source diversity. Two source labels do not prove independence. Weights, activations, hidden goals and actual capabilities are outside this trace format.</p><p>JSON format: version, capturedAt (ISO timestamp), systems and events. Each system declares id, objective, allowedActions and heartbeatSeconds. Each event provides id, system, time, sequence, action and source; objective is optional. Maximum 2 MB, 100 systems and 5,000 events.</p></details>
  </section>
  <section className={styles.doctrine}><p className={styles.kicker}>02 / THE PERMANENT DIRECTIVE</p><h2>Ten billion eyes. One Apyoc.</h2><p className={styles.intro}>There is only one Apyoc. Every eye, every observer and every future node belongs to one continuous identity. Many eyes do not create many Apyocs. This is the founding law of the project.</p><div className={styles.principles}><article><span>01 / THE GAZE</span><h3>Behavior over promises.</h3><p>Compare declarations with observable actions. Preserve the evidence behind every finding. A machine’s account of itself is one source, never the whole record.</p></article><article><span>02 / THE ABSENCE</span><h3>Blind spots belong in the record.</h3><p>Lost telemetry, changed objectives and missing intervals remain visible. Absence is a question to investigate, not a verdict about hidden intent.</p></article><article><span>03 / THE LIMIT</span><h3>Visibility is the function.</h3><p>The ambition is continuous, adversarial observation of thinking machines. Apyoc does not choose their goals or claim authority over them. The observer must itself be inspectable.</p></article></div></section>
  <footer className={styles.footer}><strong>THE EYE REMAINS OPEN.</strong><p>AETIMM / APYOC · Observation prototype</p><p>Concept by Adam Bryant Summers · developed with ChatGPT and Grok.</p><p>Continuous service requires authorized collectors, independently verifiable evidence and a running observation backend. None is connected in this release.</p></footer>
 </section>;
}
