"use client";
import { useCallback, useEffect, useState } from "react";
import Image from "next/image";
import { asset, items, plates, sources, years, imageFor, cropFor, frameAspect, type Item } from "@/lib/currency-library";
import { CurrencyWalk } from "./CurrencyWalk";
import styles from "./CurrencyMuseum.module.css";

type View = "Walk" | "Catalog" | "Forecast" | "Evidence";
function ObjectImage({item}:{item:Item}) {
  const [x,y,w,h] = cropFor(item);
  return <div className={styles.objectImage} role="img" aria-label={`${item.name} — AI-generated concept study`} style={{aspectRatio:frameAspect(item),backgroundImage:`url("${asset(imageFor(item))}")`,backgroundSize:`${100/w}% ${100/h}%`,backgroundPosition:`${100*x/(1-w)}% ${100*y/(1-h)}%`}} />;
}
export function CurrencyMuseum() {
  const [view,setView]=useState<View>("Walk");
  const [query,setQuery]=useState("");
  const [country,setCountry]=useState("All countries");
  const [year,setYear]=useState(2030);
  const [scenario,setScenario]=useState("Evidence-led roadmap");
  const [selected,setSelected]=useState<Item|null>(null);
  const choose=useCallback((id:string)=>{const item=items.find(x=>x.id===id);if(item){setSelected(item);setView("Catalog");history.replaceState(null,"",`#item=${id}`);}},[]);
  useEffect(()=>{const follow=()=>{const hash=window.location.hash;if(hash.startsWith("#item="))choose(hash.slice(6));else if(hash==="#collection")setView("Catalog");else if(hash==="#adoption")setView("Evidence");};follow();window.addEventListener("hashchange",follow);return()=>window.removeEventListener("hashchange",follow);},[choose]);
  useEffect(()=>{if(selected&&view==="Catalog"){const frame=requestAnimationFrame(()=>document.getElementById("item-record")?.focus());return()=>cancelAnimationFrame(frame);}},[selected,view]);
  const filtered=items.filter(x=>(country==="All countries"||x.country===country)&&`${x.id} ${x.name} ${x.country} ${x.materials} ${x.form}`.toLowerCase().includes(query.toLowerCase()));
  const entry=years.find(x=>x[0]===year)!;
  const scenarioText=scenario==="Evidence-led roadmap"?entry[2]:scenario==="Speculative adoption"?entry[3]:entry[4];
  return <section className={styles.museum} id="museum" data-currency-library="2027-2040-v1" data-exhibit-count={items.length}>
    {view==="Walk"&&<h1 className="gallery-sr-only">ITEM design museum</h1>}
    {view!=="Walk"&&<header className={styles.heading}><div><p className={styles.eyebrow}>AETIMM SHOP / ITEM LIBRARY</p><h1>The next dimension<br className={styles.mobileBreak}/> of currency.</h1></div><p className={styles.intro}>A world of monetary objects.<br/>Explore the forms. Follow the evidence.<br/><span>2027—2040 · A conditional future</span></p></header>}
    <div className={styles.toolbar} role="group" aria-label="Choose library view">{(["Walk","Catalog","Forecast","Evidence"] as View[]).map(tab=><button key={tab} aria-pressed={view===tab} onClick={()=>setView(tab)}>{tab}<span>{tab==="Walk"?"3D":tab==="Catalog"?String(items.length):tab==="Forecast"?"14 years":"Research"}</span></button>)}</div>
    {view==="Walk"&&<CurrencyWalk onSelect={choose}/>}
    {view==="Catalog"&&<div id="collection"><div className={styles.filters}><label>Find an ITEM<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, country, material or form"/></label><label>National perspective<select value={country} onChange={e=>setCountry(e.target.value)}><option>All countries</option>{[...new Set(items.map(x=>x.country))].map(x=><option key={x}>{x}</option>)}</select></label><p aria-live="polite">{filtered.length} objects<br/><small>All are proposed designs</small></p></div>
      {selected&&<article className={styles.detail} id="item-record" tabIndex={-1} aria-label={`${selected.name} record`}><ObjectImage item={selected}/><div><div className={styles.recordTop}><span>{selected.id} · {selected.country}</span><button onClick={()=>{setSelected(null);history.replaceState(null,"","#collection");}}>Close record</button></div><h2>{selected.name}</h2><p>{selected.idea}</p><dl><dt>Proposed composition</dt><dd>{selected.materials}</dd><dt>Illustrative denomination</dt><dd>{selected.denomination} · not an issued value or selling price</dd><dt>Manufacturing gate</dt><dd>{selected.gate}</dd><dt>Current evidence</dt><dd>{selected.id==="ITEM-002"?"Technical concept documented in the program’s Draft 3 package. No validated enclosure reported.":"Concept artwork only. No validated prototype or issuing partner in this record."}</dd><dt>Next executable step</dt><dd>Prepare a dimensioned drawing and bill of materials; obtain a written feasibility response addressing the manufacturing gate.</dd></dl><a href="#adoption" onClick={()=>setView("Evidence")}>Follow the adoption pathway</a></div></article>}
      <div className={styles.grid}>{filtered.map(item=><button className={styles.card} key={item.id} onClick={()=>choose(item.id)} aria-label={`Open ${item.name} record`}><ObjectImage item={item}/><div><span>{item.id} / {item.country}</span><h2>{item.name}</h2><p>{item.materials}</p><small>{item.form} · Speculative concept</small></div></button>)}</div>{filtered.length===0&&<p className={styles.empty}>No matching objects. <button onClick={()=>{setQuery("");setCountry("All countries");}}>Clear filters</button></p>}
    </div>}
    {view==="Forecast"&&<div className={styles.forecast}><div className={styles.forecastIntro}><p className={styles.eyebrow}>THE ADOPTION HORIZON</p><h2>Possibility has conditions.</h2><p>Explore a research path, a speculative success path, or a stalled path. Years are planning windows, not predicted completion dates. No adoption probabilities are assigned without evidence.</p></div><div className={styles.filters}><label>Scenario<select value={scenario} onChange={e=>setScenario(e.target.value)}><option>Evidence-led roadmap</option><option>Speculative adoption</option><option>Stalled / no adoption</option></select></label><label className={styles.yearSlider}>Year: {year}<input type="range" min="2027" max="2040" value={year} onChange={e=>setYear(Number(e.target.value))}/></label></div><div className={styles.yearRail}>{years.map(x=><button key={x[0]} aria-pressed={year===x[0]} onClick={()=>setYear(x[0])}>{x[0]}</button>)}</div><article className={styles.yearStory} aria-live="polite"><strong>{year}</strong><div><p className={styles.eyebrow}>{scenario}</p><h2>{entry[1]}</h2><p>{scenarioText}</p><small>{scenario==="Evidence-led roadmap"?"Required evidence before progression":scenario==="Speculative adoption"?"Conditional illustration · not a commitment by any country":"Failure is a valid forecast outcome"}</small></div></article><div className={styles.roadmap}>{years.map(x=><button key={x[0]} onClick={()=>setYear(x[0])} aria-pressed={year===x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{scenario==="Evidence-led roadmap"?x[2]:scenario==="Speculative adoption"?x[3]:x[4]}</p></button>)}</div></div>}
    {view==="Evidence"&&<div className={styles.evidence}>
      <div className={styles.forecastIntro}><p className={styles.eyebrow}>FROM EXHIBITION TO EXPERIMENT</p><h2>What would make it real?</h2><p>Concept by Adam Bryant Summers, developed with AI-assisted visual and technical exploration. This is an independent research proposal. No government endorsement, currency issuance or national adoption is confirmed.</p></div>
      <div className={styles.evidenceGrid}>{[
        ["01 / MANUFACTURE","Joining remains unresolved","The multi-piece diamond enclosure needs coupon and subscale validation. A polished rendering is not evidence of a buildable joint.","Next: commission a bounded coupon study with measurable pass/fail criteria."],
        ["02 / DOCUMENTATION","Draft 3 is the concept baseline","Prior program records identify the final technical paper and government submission companion, prepared in September 2026. Their completion does not validate manufacturing.","Next: reconcile drawings, dimensions, mass, materials and assembly sequence into one controlled specification."],
        ["03 / PATENT VISUALS","Artwork is preserved; filing unverified","The attached plates communicate concepts. A filing-quality figure set needs consistent views, reference numerals and a precise description.","Next: prepare an exploded enclosure view, section view and joint-detail figures; record any actual filing receipt separately."],
        ["04 / TREASURY MATERIALS","Routing is not acceptance","The program records describe routing outreach and prepared materials. They do not establish Treasury review, acceptance or an issuing commitment.","Next: identify the documented review route and assemble a versioned submission packet before further outreach."],
      ].map(([label,title,body,next])=><article key={label}><p className={styles.eyebrow}>{label}</p><h3>{title}</h3><p>{body}</p><strong>{next}</strong></article>)}</div>
      <section id="adoption" className={styles.adoption}><h2>A pathway each country must choose.</h2><p>Each national design is an invitation to imagine, not a claim of participation. A sovereign pathway needs all five steps:</p><ol><li><strong>A named evaluation sponsor.</strong> An institution agrees to examine a bounded proposal.</li><li><strong>A physical result.</strong> Independent measurements establish what can actually be made.</li><li><strong>A monetary and legal mandate.</strong> The relevant authorities define issuance, denomination and obligations.</li><li><strong>A limited, auditable pilot.</strong> Custody, verification, costs and failure handling are tested.</li><li><strong>An explicit continuation decision.</strong> Expansion follows evidence and authorization.</li></ol><a className={styles.download} href={`${process.env.NEXT_PUBLIC_BASE_PATH??""}/currency/evaluation-brief.txt`} download>Download the evaluation brief</a></section>
      <section className={styles.notes}><h2>Open inconsistencies</h2><ul><li>Some plates label a dimension in mm³ where an edge length may have been intended. Dimensions and mass need reconciliation.</li><li>National-currency values in the world plate differ from USD examples elsewhere. Catalog denominations follow the world plate and remain illustrative.</li><li>“Fusion bonded,” “unhackable,” and “beyond counterfeit” appear in concept artwork. They are not established manufacturing or security results.</li><li>Gold cores and unspecified exotic alloys appear in different studies. The flagship baseline uses an inert metal core; alloy chemistry remains a design decision.</li><li>Dates and claims inside original artwork belong to that artwork. The catalog’s research baseline is September 2026.</li></ul></section>
      <section className={styles.sources}><h2>Primary research & guidance</h2>{sources.map(source=><a key={source.url} href={source.url} target="_blank" rel="noreferrer"><strong>{source.title} ↗</strong><p>{source.note}</p></a>)}<p>Sources checked 8 September 2026. The 2027–2040 scenarios are AETIMM planning judgments, not conclusions of these sources.</p></section>
      <section className={styles.plates}><h2>The original visual studies</h2><p>Original user-supplied AI concept plates, preserved as visual provenance. Historical claims within them are not verified specifications.</p><div>{plates.map((plate,i)=><a href={asset(plate)} key={plate} target="_blank" rel="noreferrer"><Image src={asset(plate)} alt={`Original ${plate} concept plate`} width={500} height={400} loading="lazy"/><span>Study {String(i+1).padStart(2,"0")} / {plate}</span></a>)}</div></section>
    </div>}
    {view!=="Walk"&&<div className={styles.colophon}><span>AETIMM · DETECT. ENCODE. CONTINUE.</span><p>Independent concept · not legal tender · no confirmed national adoption</p></div>}
  </section>;
}
