-- AETIMM Museum accession lifecycle
-- Apply after 014_independent_binary_judgments.sql.
--
-- Product law:
--   ordinary submission -> public Unjudged immediately
--   Museum candidacy never makes an Artifact private again
--   public Museum votes unlock accession slots over time
--   the highest-Museum-voted unaccessioned Artifact receives the next slot
--   public voting can never remove or replace an accession
--
-- Institutional law:
--   accession is append-only evidence
--   exceptional withdrawal is administrative, reasoned, and tombstoned
--   withdrawal never deletes the accession record
--
-- Compatibility law:
--   museum_accessions is the source of truth
--   artifacts.lane='aetimm' is only a legacy presentation mirror

begin;

create table if not exists public.museum_control (
  id smallint primary key default 1 check (id = 1),
  admission_open boolean not null default true,
  museum_votes_per_accession integer not null default 100 check (museum_votes_per_accession >= 1),
  minimum_candidate_museum_votes integer not null default 10 check (minimum_candidate_museum_votes >= 1),
  updated_at timestamptz not null default now()
);

insert into public.museum_control (
  id,
  admission_open,
  museum_votes_per_accession,
  minimum_candidate_museum_votes
)
values (1, true, 100, 10)
on conflict (id) do nothing;

alter table public.museum_control enable row level security;
revoke all on public.museum_control from public, anon, authenticated;

create table if not exists public.museum_accessions (
  accession_number bigint generated by default as identity primary key,
  artifact_id uuid not null unique references public.artifacts(id) on delete restrict,
  admitted_at timestamptz not null default now(),
  museum_votes_at_accession bigint not null check (museum_votes_at_accession >= 1),
  slop_votes_at_accession bigint not null default 0 check (slop_votes_at_accession >= 0),
  admission_rule text not null default 'community_vote_slot_v1',
  withdrawn_at timestamptz,
  withdrawal_reason text,
  withdrawn_by uuid references public.profiles(id) on delete set null,
  constraint museum_accession_withdrawal_shape check (
    (withdrawn_at is null and withdrawal_reason is null and withdrawn_by is null)
    or
    (withdrawn_at is not null and withdrawal_reason is not null)
  )
);

create index if not exists museum_accessions_admitted_idx
  on public.museum_accessions (admitted_at desc, accession_number desc);

create index if not exists artifact_votes_museum_partial_idx
  on public.artifact_votes (artifact_id)
  where judgment = 'preserve';

alter table public.museum_accessions enable row level security;

drop policy if exists "museum accessions are publicly readable" on public.museum_accessions;
create policy "museum accessions are publicly readable"
  on public.museum_accessions for select
  to anon, authenticated
  using (true);

revoke all on public.museum_accessions from public, anon, authenticated;
grant select (
  accession_number,
  artifact_id,
  admitted_at,
  museum_votes_at_accession,
  slop_votes_at_accession,
  admission_rule,
  withdrawn_at,
  withdrawal_reason
) on public.museum_accessions to anon, authenticated;

create or replace function public.get_artifact_museum_accessions(
  p_artifact_ids uuid[]
)
returns table (
  artifact_id uuid,
  accession_number bigint,
  admitted_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  requested_count integer := coalesce(cardinality(p_artifact_ids), 0);
begin
  if requested_count = 0 then
    return;
  end if;

  if requested_count > 100 then
    raise exception using
      errcode = 'P0001',
      message = 'MUSEUM_ACCESSION_REQUEST_TOO_LARGE';
  end if;

  return query
  select
    accessions.artifact_id,
    accessions.accession_number,
    accessions.admitted_at
  from public.museum_accessions as accessions
  where accessions.withdrawn_at is null
    and accessions.artifact_id = any(p_artifact_ids);
end;
$$;

revoke all on function public.get_artifact_museum_accessions(uuid[]) from public, anon, authenticated;
grant execute on function public.get_artifact_museum_accessions(uuid[]) to anon, authenticated;

create or replace function public.refresh_museum_accessions()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  config public.museum_control%rowtype;
  total_museum_votes bigint;
  issued_accessions bigint;
  unlocked_slots bigint;
  candidate_id uuid;
  candidate_museum_votes bigint;
  candidate_slop_votes bigint;
begin
  select *
  into config
  from public.museum_control
  where id = 1
  for update;

  if not found or not config.admission_open then
    return;
  end if;

  select count(*)::bigint
  into total_museum_votes
  from public.artifact_votes as votes
  inner join public.artifacts as artifacts
    on artifacts.id = votes.artifact_id
   and artifacts.status = 'approved'
  where votes.judgment = 'preserve';

  select count(*)::bigint
  into issued_accessions
  from public.museum_accessions;

  -- Bound each vote transaction even if an operator later changes cadence
  -- aggressively or imports a large body of historical judgment evidence.
  unlocked_slots := least(
    greatest(
      floor(total_museum_votes::numeric / config.museum_votes_per_accession)::bigint - issued_accessions,
      0
    ),
    25
  );

  while unlocked_slots > 0 loop
    select
      artifacts.id,
      count(votes.artifact_id) filter (where votes.judgment = 'preserve')::bigint,
      count(votes.artifact_id) filter (where votes.judgment = 'slop')::bigint
    into
      candidate_id,
      candidate_museum_votes,
      candidate_slop_votes
    from public.artifacts as artifacts
    left join public.artifact_votes as votes
      on votes.artifact_id = artifacts.id
    left join public.museum_accessions as accessions
      on accessions.artifact_id = artifacts.id
    where artifacts.status = 'approved'
      and accessions.artifact_id is null
    group by artifacts.id, artifacts.published_at
    having count(votes.artifact_id) filter (where votes.judgment = 'preserve') >= config.minimum_candidate_museum_votes
    order by
      count(votes.artifact_id) filter (where votes.judgment = 'preserve') desc,
      artifacts.published_at asc nulls last,
      artifacts.id asc
    limit 1;

    if candidate_id is null then
      exit;
    end if;

    insert into public.museum_accessions (
      artifact_id,
      museum_votes_at_accession,
      slop_votes_at_accession,
      admission_rule
    ) values (
      candidate_id,
      candidate_museum_votes,
      candidate_slop_votes,
      'community_vote_slot_v1'
    )
    on conflict (artifact_id) do nothing;

    -- Legacy lane is a projection for existing feed presentation only. The
    -- accession row above is the permanent institutional record.
    update public.artifacts
    set lane = 'aetimm'
    where id = candidate_id
      and status = 'approved';

    unlocked_slots := unlocked_slots - 1;
    candidate_id := null;
  end loop;

  update public.museum_control
  set updated_at = now()
  where id = 1;
end;
$$;

revoke all on function public.refresh_museum_accessions() from public, anon, authenticated;

create or replace function public.after_museum_vote_refresh_accessions()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.judgment = 'preserve' then
    perform public.refresh_museum_accessions();
  end if;
  return new;
end;
$$;

revoke all on function public.after_museum_vote_refresh_accessions() from public, anon, authenticated;

drop trigger if exists artifact_votes_refresh_museum_accessions on public.artifact_votes;
create trigger artifact_votes_refresh_museum_accessions
after insert or update of judgment on public.artifact_votes
for each row
execute function public.after_museum_vote_refresh_accessions();

create or replace function public.withdraw_museum_accession(
  p_artifact_id uuid,
  p_reason text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  caller_role text;
begin
  select role into caller_role
  from public.profiles
  where id = auth.uid();

  if caller_role is distinct from 'admin' then
    raise exception using
      errcode = 'P0001',
      message = 'ADMIN_ROLE_REQUIRED';
  end if;

  if length(trim(coalesce(p_reason, ''))) < 10 then
    raise exception using
      errcode = 'P0001',
      message = 'WITHDRAWAL_REASON_REQUIRED';
  end if;

  update public.museum_accessions
  set
    withdrawn_at = now(),
    withdrawal_reason = trim(p_reason),
    withdrawn_by = auth.uid()
  where artifact_id = p_artifact_id
    and withdrawn_at is null;

  if not found then
    raise exception using
      errcode = 'P0001',
      message = 'ACTIVE_MUSEUM_ACCESSION_NOT_FOUND';
  end if;

  -- Withdrawal is exceptional administrative action, never a public vote. The
  -- accession row remains as a tombstone; only the legacy presentation mirror
  -- returns to Unjudged.
  update public.artifacts
  set lane = 'unjudged'
  where id = p_artifact_id
    and status = 'approved'
    and lane = 'aetimm';
end;
$$;

revoke all on function public.withdraw_museum_accession(uuid,text) from public, anon, authenticated;
grant execute on function public.withdraw_museum_accession(uuid,text) to authenticated;

commit;
